version: '3.1'

services:
  db_AuthServ:
      container_name: db_AuthServ
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      image: postgres:15-alpine
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      command:
        - 'postgres'
        - '-c'
        - 'port=${POSTGRES_PORT}'
      volumes:
        - db_AuthServ_vol:/var/lib/postgresql/data
      networks:
        - server_net

volumes: 
  db_AuthServ_vol: {}

networks:
  server_net:
    driver: bridge