services:
  db_AuthServ:
      container_name: db_AuthServ
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      image: postgres:15-alpine
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      command:
        - 'postgres'
        - '-c'
        - 'port=${POSTGRES_PORT}'
      volumes:
        - db_AuthServ_vol:/var/lib/postgresql/data
      networks:
        - server_net
  auth:
    container_name: auth
    build: ./auth
    depends_on:
      - db_AuthServ
    networks:
      - server_net
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    environment:
      AUTH_PORT: ${AUTH_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USE_SSL: ${POSTGRES_USE_SSL}

volumes: 
  db_AuthServ_vol: {}

networks:
  server_net:
    driver: bridge